### ISSUE TITLE
create configuration file to read database credentials

### ISSUE THREAD

**Issue by dip77** [dip77/Bus-Reservation-and-Pass-Creation-System#2]
currently, MysqlConnection.java has credentials for DB, need properties to file from where it will take the configuration.

**Comment by kaggrwal** [comment]
Can you assign it to me?

**Comment by dip77** [comment]
assigned. put any questions here itself.

**Comment by kaggrwal** [comment]
done, merge this https://github.com/dip77/Bus-Reservation-and-Pass-Creation-System/pull/4
